# Generated by Django 3.1.7 on 2021-02-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_id', models.CharField(max_length=100)),
                ('assay_id_sec', models.CharField(max_length=100)),
                ('gene', models.CharField(max_length=100)),
                ('sequence', models.CharField(max_length=500)),
                ('ref_build', models.CharField(choices=[('hg38', 'GRCh38'), ('hg19', 'GRCh37')], default='hg38', max_length=4)),
                ('chromosome', models.IntegerField(choices=[(1, 'Chromosome 1'), (2, 'Chromosome 2'), (3, 'Chromosome 3'), (4, 'Chromosome 4'), (5, 'Chromosome 5'), (6, 'Chromosome 6'), (7, 'Chromosome 7'), (8, 'Chromosome 8'), (9, 'Chromosome 9'), (10, 'Chromosome 10'), (11, 'Chromosome 11'), (12, 'Chromosome 12'), (13, 'Chromosome 13'), (14, 'Chromosome 14'), (15, 'Chromosome 15'), (16, 'Chromosome 16'), (17, 'Chromosome 17'), (18, 'Chromosome 18'), (19, 'Chromosome 19'), (20, 'Chromosome 20'), (21, 'Chromosome 21'), (22, 'Chromosome 22'), (23, 'Chromosome 23'), (24, 'Chromosome 24'), (25, 'Chromosome 25')])),
                ('position_from', models.IntegerField(default=0)),
                ('position_to', models.IntegerField(default=0)),
                ('transcript', models.CharField(max_length=100)),
                ('cdna', models.CharField(max_length=100)),
                ('protein', models.CharField(max_length=100)),
                ('temperature', models.IntegerField(default=55)),
                ('status', models.IntegerField(choices=[(1, 'Design failed'), (2, 'Run failed'), (3, 'Gradient PCR'), (4, 'Ok')])),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enzyme', models.CharField(choices=[('A1', 'Alui'), ('C1', 'Cviqi'), ('D2', 'Dpnii'), ('Ha3', 'Haeiii'), ('Hi3', 'Hindiii'), ('Mse1', 'Msei'), ('Msp1', 'Mspi'), ('S1', 'Smai')], max_length=4)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assaytype')),
            ],
        ),
        migrations.CreateModel(
            name='AssayPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(null=True, verbose_name='date added')),
                ('comment', models.CharField(max_length=500)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assaytype')),
            ],
        ),
        migrations.CreateModel(
            name='AssayLOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(verbose_name='date ordered')),
                ('date_scanned', models.DateTimeField(null=True, verbose_name='date scanned')),
                ('lot', models.CharField(max_length=10)),
                ('date_validated', models.DateTimeField(null=True, verbose_name='date validated')),
                ('test_id', models.CharField(max_length=20)),
                ('date_activated', models.DateTimeField(null=True, verbose_name='date activated')),
                ('volume_low', models.BooleanField(default=False)),
                ('date_inactivated', models.DateTimeField(null=True, verbose_name='date inactivated')),
                ('freezer_id', models.CharField(max_length=10)),
                ('box_position', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=500)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assaytype')),
            ],
        ),
    ]
