# Generated by Django 3.1.7 on 2021-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210317_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assaylot',
            options={'ordering': ['assay', 'date_order']},
        ),
        migrations.AlterModelOptions(
            name='assaytype',
            options={'ordering': ['chromosome', 'position_from']},
        ),
        migrations.AddField(
            model_name='assaylot',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('scanned', 'Scanned'), ('validated', 'Validated'), ('activated', 'Activated'), ('inactivated', 'Inactivated')], default='ordered', max_length=15),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='box_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date activated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_inactivated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date inactivated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_scanned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date scanned'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date validated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='freezer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assaypatient',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='assay_id_sec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='enzyme',
            field=models.ManyToManyField(help_text='Select enzymes for this assay.', to='app.Enzyme'),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='sequence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='temperature',
            field=models.IntegerField(blank=True, default=55, null=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='name',
            field=models.CharField(choices=[('A1', 'Alui'), ('C1', 'Cviqi'), ('D2', 'Dpnii'), ('Ha3', 'Haeiii'), ('Hi3', 'Hindiii'), ('Mse1', 'Msei'), ('Msp1', 'Mspi'), ('S1', 'Smai')], max_length=4),
        ),
    ]
