# Generated by Django 3.1.7 on 2021-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210325_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assaylot',
            name='test_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
