# Generated by Django 3.1.7 on 2021-04-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210325_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assaylot',
            options={'ordering': ['assay', 'date_activated'], 'permissions': (('can_update', 'Update assay lot'),)},
        ),
    ]
