# Generated by Django 3.1.7 on 2021-05-11 10:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210407_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assaylot',
            name='date_order',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='date ordered'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
