# Generated by Django 3.1.7 on 2021-06-14 13:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210511_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assaypatient',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='assaytype',
            name='tube_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fe5b01c00d0>')], verbose_name='date activated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_inactivated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fe5b01c00d0>')], verbose_name='date inactivated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_order',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fe5b01c00d0>')], verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_scanned',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is 2021-06-14 13:24:23.648830+00:00')], verbose_name='date scanned'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fe5b01c00d0>')], verbose_name='date validated'),
        ),
        migrations.AlterField(
            model_name='assaypatient',
            name='date_added',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fe5b01c00d0>')], verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='position_from',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='position_to',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='name',
            field=models.CharField(choices=[('AluI', 'Alui'), ('CviQI', 'Cviqi'), ('DpnII', 'Dpnii'), ('HaeIII', 'Haeiii'), ('HindIII', 'Hindiii'), ('MseI', 'Msei'), ('MspI', 'Mspi'), ('SmaI', 'Smai'), ('None', 'None')], max_length=10),
        ),
    ]
