# Generated by Django 3.1.7 on 2021-06-16 07:04

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210614_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assaylot',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fd9f81180d0>')], verbose_name='date activated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_inactivated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fd9f81180d0>')], verbose_name='date inactivated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_order',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fd9f81180d0>')], verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_scanned',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is 2021-06-16 07:04:56.131518+00:00')], verbose_name='date scanned'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fd9f81180d0>')], verbose_name='date validated'),
        ),
        migrations.AlterField(
            model_name='assaypatient',
            name='date_added',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fd9f81180d0>')], verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='chromosome',
            field=models.IntegerField(choices=[(1, 'Chromosome 1'), (2, 'Chromosome 2'), (3, 'Chromosome 3'), (4, 'Chromosome 4'), (5, 'Chromosome 5'), (6, 'Chromosome 6'), (7, 'Chromosome 7'), (8, 'Chromosome 8'), (9, 'Chromosome 9'), (10, 'Chromosome 10'), (11, 'Chromosome 11'), (12, 'Chromosome 12'), (13, 'Chromosome 13'), (14, 'Chromosome 14'), (15, 'Chromosome 15'), (16, 'Chromosome 16'), (17, 'Chromosome 17'), (18, 'Chromosome 18'), (19, 'Chromosome 19'), (20, 'Chromosome 20'), (21, 'Chromosome 21'), (22, 'Chromosome 22'), (23, 'Chromosome 23'), (24, 'Chromosome 24'), (25, 'Chromosome 25')], default=1),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Design failed'), (2, 'Run failed'), (3, 'Gradient PCR'), (4, 'Ok')]),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='temperature',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
