# Generated by Django 3.1.7 on 2021-06-16 09:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210616_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assaylot',
            old_name='freezer_id',
            new_name='fridge_id',
        ),
        migrations.AddField(
            model_name='assaylot',
            name='box_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assaytype',
            name='assay_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fb3f83410d0>')], verbose_name='date activated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_inactivated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fb3f83410d0>')], verbose_name='date inactivated'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_order',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fb3f83410d0>')], verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_scanned',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is 2021-06-16 09:51:41.398613+00:00')], verbose_name='date scanned'),
        ),
        migrations.AlterField(
            model_name='assaylot',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fb3f83410d0>')], verbose_name='date validated'),
        ),
        migrations.AlterField(
            model_name='assaypatient',
            name='date_added',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='Make sure the date is not in the future. Todays date is <function now at 0x7fb3f83410d0>')], verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='assaytype',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Design failed'), (2, 'Run failed'), (3, 'Gradient PCR'), (4, 'Ok')], default=0),
        ),
    ]
