name: Publish Docker image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v1
      - 
        name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.2.1
      - 
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            marrip/where_my_assays_at
          tags: |
            latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
